notifications:
  email: false
git:
  depth: 1
  submodules: true
services:
  - docker
env:
  - GO11MODULE=on  
language: go
go:
  - 1.12.6
go_import_path: github.com/kscout/serverless-registry-api
before_install:
  - sudo apt-get install -y httpie coreutils
install: go mod download
script: which realpath
