#!/usr/bin/env bash
#?
# tmpk - Temporary Kubernetes cluster control
#
# USAGE
#
#    tmpk ...
#
# OPTIONS / ARGUMENTS
#
#    All options and arguments are forwarded to the kubectl binary.
#
# ENVIRONMENT VARIABLES
#
#    TMPK_TOKEN          Cluster API token
#    TMPK_N              Temporary cluster number
#    KUBENS_NAMESPACE    (Optional) If set will provide the namespace argument to kubectl
#
# BEHAVIOR
#
#    Provides authenication options required to connect to the temporary
#    Open Shift 4 Kubernetes cluster.
#
#    Cluster API is located at the URL:
#
#        https://api.tkurian${TMPK_N}.devcluster.openshift.com:6443
#
#    TMPK_N changes based on the day.
#
#?

# {{{1 Helpers
function die() {
    echo "Error: $@" >&2
    exit 1
}

# {{{1 Check environment variables set
missing_envs=()
if [ -z "$TMPK_TOKEN" ]; then
    missing_envs+=("TMPK_TOKEN")
fi

if [ -z "$TMPK_N" ]; then
    missing_envs+=("TMPK_N")
fi

if [ -n "$missing_envs" ]; then
    die "${missing_envs[@]} environment variable(s) must be set"
fi

if [ -n "$KUBENS_NAMESPACE" ]; then
    ns_opt="--namespace $KUBENS_NAMESPACE"
fi

# {{{1 Run kubectl
exec kubectl \
     $ns_opt \
     --insecure-skip-tls-verify \
     --token "$TMPK_TOKEN" \
     --server "https://api.tkurian$TMPK_N.devcluster.openshift.com:6443" \
     "$@"
