apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ .config.env }}-serverless-registry-api
  labels:
    app: serverless-registry-api
    env: {{ .config.env }}
spec:
  replicas: 1
  selector:
    app: serverless-registry-api
    env: {{ .config.env }}
  triggers:
    - type: ImageChange
      imageChangeParams:
        containerNames:
          - serverless-registry-api
        from:
          kind: ImageStreamTag
          name: serverless-registry-api:{{ .config.env }}-latest
  template:
    metadata:
      labels:
        app: serverless-registry-api
        env: {{ .config.env }}
    spec:
      volumes:
        - name: gh-api-configuration
          secret:
            secretName: {{ .config.env }}-gh-api-configuration
      containers:
        - name: serverless-registry-api
          image: kscout/serverless-registry-api:{{ .config.env }}-latest
          env:
            - name: APP_HTTP_ADDR
              value: ":5000"
            - name: APP_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .config.env }}-db-config
                  key: mongoUser
            - name: APP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .config.env }}-mongo-credentials
                  key: password
            - name: APP_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .config.env }}-db-config
                  key: mongoDbName
            - name: APP_DB_HOST
              value: $({{ .config.env | strings.ToUpper }}_MONGO_SERVICE_HOST)
            - name: APP_GH_PRIVATE_KEY_PATH
              value: /mnt/gh-api-config/privateKey
            - name: APP_GH_INTEGRATION_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .config.env }}-gh-api-configuration
                  key: ghIntegrationID
            - name: APP_GH_INSTALLATION_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .config.env }}-gh-api-configuration
                  key: ghInstallationID
            - name: APP_GH_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .config.env }}-gh-api-configuration
                  key: webhookSecret
          volumeMounts:
            - name: gh-api-configuration
              mountPath: /mnt/gh-api-config
              readOnly: true
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP              
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .config.env }}-serverless-registry-api
  labels:
    app: serverless-registry-api
    env: {{ .config.env }}
spec:
  type: ClusterIP
  selector:
    app: serverless-registry-api
    env: {{ .config.env }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .config.env }}-serverless-registry-api
  labels:
    app: serverless-registry-api
    env: {{ .config.env }}
spec:
  host: {{ .config.host }}
  path: /
  to:
    kind: Service
    name: {{ .config.env }}-serverless-registry-api
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
status:
  ingress:
    - host: api.kscout.io
