apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-serverless-registry-api
  labels:
    app: serverless-registry-api
    component: api
    env: {{ .Values.env }}
spec:
  type: ClusterIP
  selector:
    app: serverless-registry-api
    component: api
    env: {{ .Values.env }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: proxy-http
      name: proxy-http
