apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: app-api
  namespace: knative-scout
  labels:
    app: app-api
spec:
  dockerImageRepository: docker.io/kscout/app-api
  tags:
    - from:
        kind: DockerImage
        name: docker.io/kscout/app-api
      name: master
      importPolicy:
        scheduled: true
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: app-api
  namespace: knative-scout
  labels:
    app: app-api
spec:
  replicas: 1
  selector:
    app: app-api
  triggers:
    - type: ImageChange
      imageChangeParams:
        containerNames:
          - app-api
        from:
          kind: ImageStreamTag
          name: app-api:master
  template:
    metadata:
      labels:
        app: app-api
    spec:
      containers:
        - name: app-api
          image: docker.io/kscout/app-api:master
          env:
            - name: APP_HTTP_ADDR
              value: ":5000"
            - name: APP_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: mongoUser
            - name: APP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password
            - name: APP_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: mongoDbName
            - name: APP_DB_HOST
              value: $(MONGO_SERVICE_HOST)
            - name: APP_GH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gh-api-configuration
                  key: apiToken
            - name: APP_GH_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: gh-api-configuration
                  key: webhookSecret
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: app-api
  namespace: knative-scout
  labels:
    app: app-api
spec:
  type: ClusterIP
  selector:
    app: app-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: app-api
  namespace: knative-scout
  labels:
    app: app-api
spec:
  host: api.kscout.io
  path: /
  to:
    kind: Service
    name: app-api
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
status:
  ingress:
    - host: api.kscout.io
      
