apiVersion: v1
kind: Namespace
metadata:
  name: lets-encrypt
---
apiVersion: v1
kind: ClusterRole
metadata:
  name: openshift-acme
  namespace: lets-encrypt
  labels:
    app: openshift-acme
rules:
- apiGroups:
  - "route.openshift.io"
  resources:
  - routes
  - routes/finalizers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete

- apiGroups:
  - "route.openshift.io"
  resources:
  - routes/custom-host
  verbs:
  - create
  - update
  - delete
  - patch

- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch

- apiGroups:
  - ""
  resources:
  - endpoints
  - endpoints/restricted
  - services
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete

- apiGroups:
  - ""
  resources:
  - secrets
  - secrets/finalizers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: openshift-acme
  namespace: lets-encrypt
  labels:
    app: openshift-acme
---
apiVersion: v1
kind: ImageStream
metadata:
  name: openshift-acme
  namespace: lets-encrypt
  labels:
    app: openshift-acme
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: docker.io/tnozicka/openshift-acme:latest
    importPolicy:
      scheduled: true
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: openshift-acme
  namespace: lets-encrypt
  labels:
    app: openshift-acme
  annotations:
    image.alpha.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"openshift-acme:latest"},"fieldPath":"spec.template.spec.containers[0].image"}]'
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"openshift-acme:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"openshift-acme\")].image"}]'
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openshift-acme
    spec:
      serviceAccountName: openshift-acme
      containers:
      - name: openshift-acme
        image: " "
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: OPENSHIFT_ACME_EXPOSER_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: OPENSHIFT_ACME_ACMEURL
          value: "https://acme-v01.api.letsencrypt.org/directory"
        - name: OPENSHIFT_ACME_LOGLEVEL
          value: "4"
