apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: knative-scout
  labels:
    app: app-api
type: Opaque
data:
  password: BASE64_ENCODED_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: gh-api-credentials
  namespace: knative-scout
  labels:
    app: app-api
type: Opaque
data:
  token: BASE64_ENCODED_TOKEN
  
