# Global shared chart configuration
global:
  # Deployment environment, usually "prod" or "staging"
  #env: 

  # App being deployed
  app: serverless-registry-api

# HTTP service chart
http:
  # Serve under host
  defaultHost: api.kscout.io

  # Internal app container port
  port: 5000

  # Enable metrics
  metricsEnabled: true
  metricsPort: 9090

  # Configuration
  configMap:
    - key: externalURL
      value: "https://{{ .Values.defaultHost }}"
      envKey: APP_EXTERNAL_URL
    - key: apiAddr
      value: ":{{ .Values.port }}"
      envKey: APP_API_ADDR
    - key: metricsAddr
      value: ":{{ .Values.metricsPort }}"
      envKey: APP_METRICS_ADDR
    - key: ghPrivateKeyPath
      value: /mnt/secret/ghPrivateKey
      envKey: APP_GH_PRIVATE_KEY_PATH

  # Mount secret under path
  secretMount: /mnt/secret

  # Pass Mongo credentials to app container
  mongoEnabled: true
