# Deployment environment, usually "prod" or "staging"
#env: 

# Host to deploy service under. Defaults to www.kscout.io if env is prod.
# Otherwise defaults to ENV-www.kscout.io
#host: 

# Configures mongo sub-chart
mongo:
  app: serverless-registry-api
